Feat/rm legacy
kazhuravlev/options-gen pull request #31
Opened 2022-09-01 18:05 UTC by Antonboom

Looks after https://github.com/kazhuravlev/options-gen/pull/28 merge.

Closes:

- https://github.com/kazhuravlev/options-gen/issues/16
- https://github.com/kazhuravlev/options-gen/issues/29
- https://github.com/kazhuravlev/options-gen/issues/30

Changelog:

- Remove legacy tags.
- Do not generate extra code without necessary.
- Validate functions became private.
- Use tabs instead of spaces.
- `optOptionsMeta struct` -> `optionsSetter func`

2022-09-07 19:04 UTC, Antonboom commented
> Could you fix them?

Done

2022-09-10 11:04 UTC, kazhuravlev requested changes

2022-09-11 17:11 UTC, Antonboom commented on internal/generator/generator.go
> -		case "required":
@kazhuravlev, I did it via hack :) 

Check please

2022-09-12 21:48 UTC, kazhuravlev commented on internal/generator/generator.go
> -		case "required":
It is not working as the previous version, but I think we can accept that)

2022-09-12 21:49 UTC, kazhuravlev approved these changes

2022-09-12 21:55 UTC, merged